#!/usr/bin/env python3
"""fleet-html-report builder (ccc-node #2109 C).

Turns a small JSON spec into ONE self-contained HTML file (inline CSS, no
JavaScript, no external requests) and writes it under an ``artifacts``
directory so the bridge delivers it as an attachment (core/deliverables.py
admits html/htm only under ``…/artifacts/…``). Every value is HTML-escaped;
status words (ok/warn/fail/n/a/info/pending) get a colour chip.

Spec (UTF-8 JSON):
  {"title": "플릿 self-update 매트릭스", "subtitle": "2026-10-02 15:00 KST (node-b)",
   "sections": [
     {"kind": "table", "title": "노드별 상태", "columns": ["node", "harness", "bridge"],
      "rows": [["node-a", "ok", "warn"], ["node-b", "ok", "ok"]]},
     {"kind": "kv", "title": "요약", "items": [["브로커", "a930ce8b"], ["워커", "6/6 online"]]},
     {"kind": "list", "title": "다음 액션", "items": ["관측 창 18:00 KST", "..."]},
     {"kind": "text", "title": "메모", "text": "자유 문단"}],
   "footer": "generated by fleet-html-report"}

Usage:
  build_html_report.py --spec spec.json --out <artifacts-dir-or-file.html> [--name fleet-report]
Prints one JSON line: {"ok": true, "file": "...", "bytes": N}. Exit 2 on a bad
spec, 3 when the output path has no ``artifacts`` directory component (the
bridge would not send it). Never put secrets in a spec — values are rendered.
"""
from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path

ARTIFACT_DIR_NAME = "artifacts"
STATUS_COLORS = {
    "ok": "#2e9e5b",
    "warn": "#d9a400",
    "fail": "#c93b3b",
    "n/a": "#9a9a9a",
    "info": "#3b74c9",
    "pending": "#b48bd9",
}
MAX_SECTIONS = 40
MAX_ROWS = 500
MAX_CELL = 400
CSS = """
:root{color-scheme:light dark}
body{font-family:"Noto Sans CJK KR","Noto Sans KR","NanumGothic","Apple SD Gothic Neo","DejaVu Sans",sans-serif;
 margin:24px auto;max-width:960px;padding:0 16px;color:#1f2933;background:#fff;line-height:1.45}
@media (prefers-color-scheme:dark){body{color:#e5e9ee;background:#14181d}table{border-color:#2c343c}th,td{border-color:#2c343c}th{background:#1c2229}.kv dt{color:#9fb0c0}}
h1{font-size:22px;margin:0 0 4px}.sub{color:#6b7a89;margin:0 0 20px;font-size:13px}
h2{font-size:16px;margin:24px 0 8px;border-bottom:1px solid #d5dbe1;padding-bottom:4px}
table{border-collapse:collapse;width:100%;font-size:14px;border:1px solid #d5dbe1}
th,td{border:1px solid #d5dbe1;padding:6px 10px;text-align:left;vertical-align:top}
th{background:#f4f6f8;font-weight:600}
.chip{display:inline-block;padding:1px 8px;border-radius:10px;color:#fff;font-size:12px;font-weight:600}
.kv{display:grid;grid-template-columns:max-content 1fr;gap:4px 16px;font-size:14px;margin:0}
.kv dt{color:#5b6b7a;margin:0}.kv dd{margin:0}
ul{padding-left:20px;font-size:14px}p{font-size:14px;white-space:pre-wrap}
footer{margin-top:32px;color:#8a97a5;font-size:12px}
"""


class SpecError(ValueError):
    pass


def _s(value, limit=MAX_CELL) -> str:
    text = "" if value is None else str(value)
    return text if len(text) <= limit else text[: limit - 1] + "…"


def _esc(value) -> str:
    return html.escape(_s(value), quote=True)


def _cell(value) -> str:
    text = _s(value)
    key = text.strip().lower()
    if key in STATUS_COLORS:
        return f'<span class="chip" style="background:{STATUS_COLORS[key]}">{html.escape(text)}</span>'
    return html.escape(text)


def _section_table(sec: dict) -> str:
    cols = sec.get("columns")
    rows = sec.get("rows")
    if not isinstance(cols, list) or not cols or not isinstance(rows, list):
        raise SpecError("table needs columns[] and rows[]")
    if len(rows) > MAX_ROWS:
        raise SpecError("table too large")
    if any(not isinstance(r, list) or len(r) != len(cols) for r in rows):
        raise SpecError("every table row must have one cell per column")
    head = "".join(f"<th>{_esc(c)}</th>" for c in cols)
    body = "".join("<tr>" + "".join(f"<td>{_cell(v)}</td>" for v in r) + "</tr>" for r in rows)
    return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"


def _section_kv(sec: dict) -> str:
    items = sec.get("items")
    if not isinstance(items, list) or any(not isinstance(i, list) or len(i) != 2 for i in items):
        raise SpecError("kv needs items[[key, value], …]")
    if len(items) > MAX_ROWS:
        raise SpecError("kv too large")
    return '<dl class="kv">' + "".join(f"<dt>{_esc(k)}</dt><dd>{_cell(v)}</dd>" for k, v in items) + "</dl>"


def _section_list(sec: dict) -> str:
    items = sec.get("items")
    if not isinstance(items, list):
        raise SpecError("list needs items[]")
    if len(items) > MAX_ROWS:
        raise SpecError("list too large")
    return "<ul>" + "".join(f"<li>{_cell(i)}</li>" for i in items) + "</ul>"


def _section_text(sec: dict) -> str:
    return f"<p>{_esc(_s(sec.get('text'), 20000))}</p>"


_SECTIONS = {"table": _section_table, "kv": _section_kv, "list": _section_list, "text": _section_text}


def build_html(spec: dict) -> str:
    if not isinstance(spec, dict):
        raise SpecError("spec must be a JSON object")
    title = _s(spec.get("title"), 200) or "report"
    sections = spec.get("sections")
    if not isinstance(sections, list) or not sections:
        raise SpecError("spec needs non-empty sections[]")
    if len(sections) > MAX_SECTIONS:
        raise SpecError("too many sections")
    parts = [
        "<!doctype html>", '<html lang="ko"><head><meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        '<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; img-src data:">',
        f"<title>{_esc(title)}</title>", f"<style>{CSS}</style></head><body>",
        f"<h1>{_esc(title)}</h1>",
    ]
    subtitle = _s(spec.get("subtitle"), 300)
    if subtitle:
        parts.append(f'<p class="sub">{_esc(subtitle)}</p>')
    for sec in sections:
        if not isinstance(sec, dict):
            raise SpecError("each section must be an object")
        kind = _s(sec.get("kind")).lower()
        if kind not in _SECTIONS:
            raise SpecError("section kind must be one of table, kv, list, text")
        heading = _s(sec.get("title"), 200)
        if heading:
            parts.append(f"<h2>{_esc(heading)}</h2>")
        parts.append(_SECTIONS[kind](sec))
    footer = _s(spec.get("footer"), 300)
    if footer:
        parts.append(f"<footer>{_esc(footer)}</footer>")
    parts.append("</body></html>")
    return "\n".join(parts) + "\n"


def _resolve_out(out: str, name: str) -> Path:
    p = Path(out).expanduser()
    if p.suffix.lower() in (".html", ".htm"):
        return p.resolve()
    safe = "".join(ch if ch.isalnum() or ch in "-_." else "-" for ch in name).strip("-.") or "fleet-report"
    return (p / f"{safe}.html").resolve()


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--spec", required=True)
    ap.add_argument("--out", required=True, help="artifacts directory, or a file path ending in .html")
    ap.add_argument("--name", default="fleet-report")
    args = ap.parse_args(argv)
    try:
        spec = json.loads(Path(args.spec).read_text(encoding="utf-8"))
        document = build_html(spec)
    except (OSError, ValueError) as exc:  # SpecError is a ValueError
        print(json.dumps({"ok": False, "error": str(exc) if isinstance(exc, SpecError) else f"spec unreadable or not JSON: {exc.__class__.__name__}"}, ensure_ascii=False))
        return 2
    target = _resolve_out(args.out, args.name)
    if ARTIFACT_DIR_NAME not in target.parent.parts:
        print(json.dumps({"ok": False, "error": f"output must live under an '{ARTIFACT_DIR_NAME}' directory (the bridge sends html only from there)", "file": str(target)}, ensure_ascii=False))
        return 3
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(document, encoding="utf-8")
    except OSError as exc:
        print(json.dumps({"ok": False, "error": f"cannot write output: {exc.__class__.__name__}"}))
        return 4
    print(json.dumps({"ok": True, "file": str(target), "bytes": len(document.encode("utf-8"))}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
