#!/usr/bin/env bash
# distill/wiki-queue.sh
# Reads distilled JSON on stdin and appends durable wiki_candidates entries to
# ~/.claude/state/wiki-candidates.md for HUMAN review via the wiki-record skill.
# Auto-PR is intentionally NOT done here (human gate per TM-1058).
#
# De-dup: each candidate's title (lowercased, trimmed) is hashed; we maintain a
# .seen file with a TTL window (CCC_DISTILL_SEEN_TTL_DAYS, default 7 days).
# The canonical format is:
#   <first_epoch> <last_epoch> <count> <hash>
# Legacy lines are accepted as either `<epoch> <hash>` or `<hash>`.
#
# Noise controls (GitHub issue #298):
#   - at most CCC_DISTILL_MAX_WIKI_CANDS (default 3) candidates are queued per
#     session; the extractor prompt asks for the same cap, this is the
#     deterministic backstop.
#   - `wiki-queue.sh --compact` retroactively de-duplicates PENDING queue
#     entries with the same title_hash() bucket (entries queued before the
#     issue-anchored hashing existed), keeping only the newest per bucket, and
#     refreshes .seen so the surviving topics stay suppressed.
set -uo pipefail

STATE_DIR="${CCC_STATE_DIR:-${HOME:-/root}/.claude/state}"
QUEUE="$STATE_DIR/wiki-candidates.md"
SEEN="$STATE_DIR/wiki-candidates.seen"
mkdir -p "$STATE_DIR" 2>/dev/null

# Bootstrap queue file.
if [ ! -f "$QUEUE" ]; then
  cat > "$QUEUE" <<'EOF'
# Wiki Candidates Queue (auto-generated by distill; review with `/wiki-record`)

> Each entry is a durable operational fact / decision proposed by the Session
> Distiller (TM-1058). Review and either:
>   - Promote via `/wiki-record` (creates PR), then mark status: merged below.
>   - Reject by deleting the entry (or marking status: rejected).
>
> Never auto-PR — this is a human-gated queue.

EOF
fi

NOW_EPOCH="$(date -u +%s)"
# Dedup memory TTL: how long a queued topic suppresses re-extraction. Longer
# values reduce weekly re-queueing of long-running topics (issue #298).
SEEN_TTL_DAYS="${CCC_DISTILL_SEEN_TTL_DAYS:-7}"
case "$SEEN_TTL_DAYS" in ''|*[!0-9]*) SEEN_TTL_DAYS=7 ;; esac
[ "$SEEN_TTL_DAYS" -lt 1 ] && SEEN_TTL_DAYS=7
CUTOFF_EPOCH="$(date -u -d "$SEEN_TTL_DAYS days ago" +%s 2>/dev/null || echo 0)"
# Review-staleness marker stays at a fixed 7 days (independent of dedup TTL).
STALE_CUTOFF_ISO="$(date -u -d '7 days ago' +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || printf '0000-00-00T00:00:00Z')"
HOTNESS_THRESHOLD="${CCC_DISTILL_HOTNESS_THRESHOLD:-3}"
case "$HOTNESS_THRESHOLD" in ''|*[!0-9]*) HOTNESS_THRESHOLD=3 ;; esac
[ "$HOTNESS_THRESHOLD" -lt 1 ] && HOTNESS_THRESHOLD=3
MAX_WIKI_CANDS="${CCC_DISTILL_MAX_WIKI_CANDS:-3}"
case "$MAX_WIKI_CANDS" in ''|*[!0-9]*) MAX_WIKI_CANDS=3 ;; esac
[ "$MAX_WIKI_CANDS" -lt 1 ] && MAX_WIKI_CANDS=3

# title_hash: collapse cosmetic title variants so the dedup/hot mechanism
# actually catches recurring topics. Strategy:
#   A) issue-anchored — if the title mentions one or more #NNN tokens, the
#      hash is determined ONLY by the sorted set of issue numbers. That
#      handles real-world variants like:
#        "#82 distill fleet rollout: per-node smoke 절차"
#        "Issue #82: distill fleet verification checklist — 9개 노드 ..."
#        "이슈 #82: distill fleet verification per-node 체크리스트 현황"
#        "Distill Fleet Rollout (#82) 노드별 검증 체크리스트"
#      → all collapse to `i82`. Multi-issue titles like `#82/#83/#84: ...`
#      get a distinct bucket `i82-i83-i84` (operator intent differs).
#   B) sigilless — lowercase, strip section-prefix words ("Issue:", "이슈:",
#      "Decision:", etc., with required colon), strip space-bounded round
#      tokens (r10, r25), normalize common punctuation to space, collapse
#      whitespace. Backward compatible with the old hash for titles that
#      consist of plain words only (e.g. "Decision A").
title_hash() {
  local title="$1"
  local issue_sig
  issue_sig="$(printf '%s' "$title" | grep -oE '#[0-9]+' | tr -d '#' | sort -un | paste -sd- -)"
  if [ -n "$issue_sig" ]; then
    printf 'i%s' "$issue_sig" | sha256sum | cut -c1-12
    return
  fi
  # Order matters: replace punctuation (so "(r18)" -> " r18 ") BEFORE the
  # round-tag strip so space-bounded \br[0-9]+\b actually matches.
  printf '%s' "$title" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E '
        s/^[[:space:]]*(issue|이슈|결정|정책|런북|runbook|decision|spec|policy):[[:space:]]+//
        s/—/ /g
        s/–/ /g
        s/：/ /g
        s/[(),./?!]/ /g
        s/:/ /g
        s/(^| )r[0-9]+( |$)/ /g
        s/[[:space:]]+/ /g
        s/^[[:space:]]+//
        s/[[:space:]]+$//
      ' \
    | sha256sum | cut -c1-12
}

normalize_seen() {
  [ -f "$SEEN" ] || { : > "$SEEN"; return 0; }
  awk -v cutoff="$CUTOFF_EPOCH" -v now="$NOW_EPOCH" '
    function isnum(v) { return v ~ /^[0-9]+$/ }
    NF == 0 { next }
    NF == 1 {
      first=now; last=now; count=1; hash=$1
    }
    NF == 2 {
      first=$1; last=$1; count=1; hash=$2
      if (!isnum(first)) { first=now; last=now; count=1; hash=$1 }
    }
    NF >= 4 {
      first=$1; last=$2; count=$3; hash=$4
      if (!isnum(first)) first=now
      if (!isnum(last)) last=first
      if (!isnum(count) || count < 1) count=1
    }
    hash != "" && last >= cutoff {
      # Last duplicate wins if stale/manual edits created repeated hashes.
      row[hash]=first " " last " " count " " hash
    }
    END {
      for (h in row) print row[h]
    }
  ' "$SEEN" > "$SEEN.tmp" 2>/dev/null && mv "$SEEN.tmp" "$SEEN"
}

seen_row() { # <hash>
  awk -v h="$1" '$4 == h { print; exit }' "$SEEN" 2>/dev/null
}

update_seen() { # <hash> <first> <last> <count>
  local hash="$1" first="$2" last="$3" count="$4" tmp found=0
  tmp="$SEEN.tmp.$$"
  awk -v h="$hash" -v first="$first" -v last="$last" -v count="$count" '
    $4 == h { print first, last, count, h; found=1; next }
    { print }
    END { if (!found) print first, last, count, h }
  ' "$SEEN" > "$tmp" 2>/dev/null && mv "$tmp" "$SEEN"
}

mark_stale_pending() {
  [ -f "$QUEUE" ] || return 0
  awk -v cutoff="$STALE_CUTOFF_ISO" '
    function reset() { block=""; pending=0; distilled="" }
    function flush() {
      if (block == "") return
      if (pending && distilled != "" && distilled < cutoff && block !~ /\(stale: pending review\)/) {
        sub(/\n/, " (stale: pending review)\n", block)
      }
      printf "%s", block
      reset()
    }
    BEGIN { reset() }
    /^## \[CAND-[0-9]+\]/ {
      flush()
      block=$0 "\n"
      next
    }
    {
      if (block != "") {
        block = block $0 "\n"
        if ($0 ~ /^- status: pending/) pending=1
        if ($0 ~ /^- distilled-at: /) distilled=$3
      } else {
        print
      }
    }
    END { flush() }
  ' "$QUEUE" > "$QUEUE.tmp" 2>/dev/null && mv "$QUEUE.tmp" "$QUEUE"
}

# --compact: one-shot retroactive de-dup of PENDING queue entries (issue #298).
# Entries queued before issue-anchored hashing existed can share a topic bucket;
# this keeps only the NEWEST pending entry per title_hash bucket, drops the rest
# (the queue header documents deletion as the rejection mechanism), and bumps
# .seen so surviving topics stay suppressed. merged/rejected entries are kept.
compact_queue() {
  [ -f "$QUEUE" ] || { echo "wiki-queue compact: no queue file"; return 0; }
  local tmpdir
  tmpdir="$(mktemp -d)" || return 0
  awk -v dir="$tmpdir" '
    BEGIN { out=dir "/block-00000" }
    /^## \[CAND-[0-9]+\]/ { n++; out=sprintf("%s/block-%05d", dir, n) }
    { print > out }
  ' "$QUEUE"

  # Heading shape: `## [CAND-N] YYYY-MM-DD — TITLE`; a HOT re-surface carries a
  # second separator: `## [CAND-N] YYYY-MM-DD — 🔥 HOT (seen ×K) — TITLE`.
  block_hash() { # <block-file> -> title_hash of the real title ("" if no title)
    local heading title
    heading="$(head -1 "$1")"
    [ "${heading%%— *}" != "$heading" ] || { printf ''; return; }
    title="${heading#*— }"
    case "$title" in "🔥 HOT ("*"— "*) title="${title#*— }" ;; esac
    title_hash "$title"
  }

  local f hash
  declare -A winner bucket_total
  # Pass 1: newest pending block per bucket wins (ascending file order = queue order).
  for f in "$tmpdir"/block-*; do
    [ "$f" = "$tmpdir/block-00000" ] && continue
    grep -q '^- status: pending' "$f" || continue
    hash="$(block_hash "$f")"
    [ -n "$hash" ] || continue
    winner["$hash"]="$f"
    bucket_total["$hash"]=$(( ${bucket_total["$hash"]:-0} + 1 ))
  done

  local kept=0 dropped=0 row first count old
  {
    [ -f "$tmpdir/block-00000" ] && cat "$tmpdir/block-00000"
    for f in "$tmpdir"/block-*; do
      [ "$f" = "$tmpdir/block-00000" ] && continue
      if grep -q '^- status: pending' "$f"; then
        hash="$(block_hash "$f")"
        if [ -n "$hash" ] && [ "${winner["$hash"]:-}" != "$f" ]; then
          dropped=$((dropped + 1))
          continue
        fi
      fi
      cat "$f"
      kept=$((kept + 1))
    done
  } > "$QUEUE.tmp" && mv "$QUEUE.tmp" "$QUEUE"

  # Refresh .seen for surviving buckets so near-term re-extraction stays deduped.
  for hash in "${!winner[@]}"; do
    row="$(seen_row "$hash")"
    first="$NOW_EPOCH"; count="${bucket_total["$hash"]}"
    if [ -n "$row" ]; then
      first="$(printf '%s' "$row" | awk '{print $1}')"
      old="$(printf '%s' "$row" | awk '{print $3}')"
      case "$old" in ''|*[!0-9]*) old=1 ;; esac
      [ "$old" -gt "$count" ] && count="$old"
    fi
    update_seen "$hash" "$first" "$NOW_EPOCH" "$count"
  done

  rm -rf "$tmpdir"
  echo "wiki-queue compact: kept=$kept dropped(dup)=$dropped buckets=${#winner[@]}"
}

normalize_seen
mark_stale_pending

if [ "${1:-}" = "--compact" ]; then
  compact_queue
  exit 0
fi

PAYLOAD="$(cat 2>/dev/null)"
[ -n "$PAYLOAD" ] || exit 0

CANDS="$(printf '%s' "$PAYLOAD" | jq -c '.wiki_candidates // []')"
N="$(printf '%s' "$CANDS" | jq 'length')"

if [ "$N" = "0" ]; then
  echo "no wiki candidates (session=$(printf '%s' "$PAYLOAD" | jq -r .session_id))"
  exit 0
fi

# Per-session cap (issue #298): the extractor prompt asks for at most this many,
# but the prompt has no enforcement power — this truncation is the deterministic
# backstop. Extract order is the model's durability ranking, so keep the head.
TRUNCATED=0
if [ "$N" -gt "$MAX_WIKI_CANDS" ]; then
  TRUNCATED=$((N - MAX_WIKI_CANDS))
  CANDS="$(printf '%s' "$CANDS" | jq -c ".[0:$MAX_WIKI_CANDS]")"
fi

SID="$(printf '%s' "$PAYLOAD" | jq -r '.session_id // "unknown"')"
TRG="$(printf '%s' "$PAYLOAD" | jq -r '.trigger // "manual"')"
SOURCE_CWD="$(printf '%s' "$PAYLOAD" | jq -r '.source_cwd // empty')"
SOURCE_PROJECT="$(printf '%s' "$PAYLOAD" | jq -r '.source_project // empty')"
TS_LOG="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
DATE="$(date -u +%Y-%m-%d)"

# Next CAND-N id (scan existing queue file).
LAST_ID="$(grep -oE '\[CAND-[0-9]+\]' "$QUEUE" 2>/dev/null | grep -oE '[0-9]+' | sort -n | tail -1)"
[ -z "$LAST_ID" ] && LAST_ID=0
NEXT_ID=$((LAST_ID + 1))

ADDED=0
SKIPPED=0

# Iterate candidates.
LEN=$(printf '%s' "$CANDS" | jq 'length')
for i in $(seq 0 $((LEN - 1))); do
  ITEM="$(printf '%s' "$CANDS" | jq -c ".[$i]")"
  TITLE="$(printf '%s' "$ITEM" | jq -r '.title // ""' | tr -d '\r')"
  PATH_S="$(printf '%s' "$ITEM" | jq -r '.suggested_path // ""')"
  SUMMARY="$(printf '%s' "$ITEM" | jq -r '.summary // ""')"
  EVIDENCE="$(printf '%s' "$ITEM" | jq -r '.evidence_excerpt // ""')"

  [ -z "$TITLE" ] && continue

  # De-dup hash: title (normalized — see title_hash() above).
  HASH="$(title_hash "$TITLE")"

  ROW="$(seen_row "$HASH")"
  FIRST="$NOW_EPOCH"
  OLD_COUNT=0
  if [ -n "$ROW" ]; then
    FIRST="$(printf '%s' "$ROW" | awk '{print $1}')"
    OLD_COUNT="$(printf '%s' "$ROW" | awk '{print $3}')"
    case "$OLD_COUNT" in ''|*[!0-9]*) OLD_COUNT=1 ;; esac
  fi
  NEW_COUNT=$((OLD_COUNT + 1))
  update_seen "$HASH" "$FIRST" "$NOW_EPOCH" "$NEW_COUNT"

  HOT_EMIT=0
  if [ "$OLD_COUNT" -gt 0 ] && [ "$OLD_COUNT" -lt "$HOTNESS_THRESHOLD" ] && [ "$NEW_COUNT" -ge "$HOTNESS_THRESHOLD" ]; then
    HOT_EMIT=1
  fi

  if [ "$OLD_COUNT" -gt 0 ] && [ "$HOT_EMIT" != "1" ]; then
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  DISPLAY_TITLE="$TITLE"
  if [ "$HOT_EMIT" = "1" ]; then
    DISPLAY_TITLE="🔥 HOT (seen ×$NEW_COUNT) — $TITLE"
  fi

  # Append entry.
  {
    printf '\n## [CAND-%d] %s — %s\n' "$NEXT_ID" "$DATE" "$DISPLAY_TITLE"
    printf -- '- suggested-path: `%s`\n' "$PATH_S"
    printf -- '- proposed-id: TM-?? (assign at PR time)\n'
    printf -- '- source-session: `%s` (trigger=%s)\n' "$SID" "$TRG"
    [ -n "$SOURCE_CWD" ] && printf -- '- source-cwd: `%s`\n' "$SOURCE_CWD"
    [ -n "$SOURCE_PROJECT" ] && printf -- '- source-project: `%s`\n' "$SOURCE_PROJECT"
    printf -- '- distilled-at: %s\n' "$TS_LOG"
    printf -- '- status: pending\n'
    printf -- '- summary: %s\n' "$SUMMARY"
    if [ -n "$EVIDENCE" ] && [ "$EVIDENCE" != "null" ]; then
      printf -- '- evidence-excerpt: |\n'
      printf '%s\n' "$EVIDENCE" | sed 's/^/    /'
    fi
  } >> "$QUEUE"

  NEXT_ID=$((NEXT_ID + 1))
  ADDED=$((ADDED + 1))
done

echo "wiki-queue session=$SID added=$ADDED skipped(dup)=$SKIPPED total_in=$N truncated(cap)=$TRUNCATED"
