#!/usr/bin/env bash
# distill/wiki-queue.sh
# Reads distilled JSON on stdin and appends durable wiki_candidates entries to
# ~/.claude/state/wiki-candidates.md for HUMAN review via the wiki-record skill.
# Auto-PR is intentionally NOT done here (human gate per TM-1058).
#
# De-dup: each candidate's title (lowercased, trimmed) is hashed; we maintain a
# .seen file with a 7-day TTL window so identical re-surfaces don't pile up.
set -uo pipefail

STATE_DIR=/root/.claude/state
QUEUE="$STATE_DIR/wiki-candidates.md"
SEEN="$STATE_DIR/wiki-candidates.seen"
mkdir -p "$STATE_DIR" 2>/dev/null

# Bootstrap queue file.
if [ ! -f "$QUEUE" ]; then
  cat > "$QUEUE" <<'EOF'
# Wiki Candidates Queue (auto-generated by distill; review with `/wiki-record`)

> Each entry is a durable operational fact / decision proposed by the Session
> Distiller (TM-1058). Review and either:
>   - Promote via `/wiki-record` (creates PR), then mark status: merged below.
>   - Reject by deleting the entry (or marking status: rejected).
>
> Never auto-PR — this is a human-gated queue.

EOF
fi

PAYLOAD="$(cat 2>/dev/null)"
[ -n "$PAYLOAD" ] || exit 0

CANDS="$(printf '%s' "$PAYLOAD" | jq -c '.wiki_candidates // []')"
N="$(printf '%s' "$CANDS" | jq 'length')"

if [ "$N" = "0" ]; then
  echo "no wiki candidates (session=$(printf '%s' "$PAYLOAD" | jq -r .session_id))"
  exit 0
fi

SID="$(printf '%s' "$PAYLOAD" | jq -r '.session_id // "unknown"')"
TRG="$(printf '%s' "$PAYLOAD" | jq -r '.trigger // "manual"')"
TS_LOG="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
DATE="$(date -u +%Y-%m-%d)"

# Next CAND-N id (scan existing queue file).
LAST_ID="$(grep -oE '\[CAND-[0-9]+\]' "$QUEUE" 2>/dev/null | grep -oE '[0-9]+' | sort -n | tail -1)"
[ -z "$LAST_ID" ] && LAST_ID=0
NEXT_ID=$((LAST_ID + 1))

# Prune seen file (>7 days old entries dropped).
if [ -f "$SEEN" ]; then
  CUTOFF=$(date -u -d '7 days ago' +%s 2>/dev/null || echo 0)
  awk -v cutoff="$CUTOFF" '$1 >= cutoff' "$SEEN" > "$SEEN.tmp" 2>/dev/null \
    && mv "$SEEN.tmp" "$SEEN"
fi
touch "$SEEN"

NOW_EPOCH="$(date -u +%s)"
ADDED=0
SKIPPED=0

# Iterate candidates.
LEN=$(printf '%s' "$CANDS" | jq 'length')
for i in $(seq 0 $((LEN - 1))); do
  ITEM="$(printf '%s' "$CANDS" | jq -c ".[$i]")"
  TITLE="$(printf '%s' "$ITEM" | jq -r '.title // ""' | tr -d '\r')"
  PATH_S="$(printf '%s' "$ITEM" | jq -r '.suggested_path // ""')"
  SUMMARY="$(printf '%s' "$ITEM" | jq -r '.summary // ""')"
  EVIDENCE="$(printf '%s' "$ITEM" | jq -r '.evidence_excerpt // ""')"

  [ -z "$TITLE" ] && continue

  # De-dup hash: title (normalized).
  HASH="$(printf '%s' "$TITLE" | tr '[:upper:]' '[:lower:]' | tr -s ' ' \
    | sha256sum | cut -c1-12)"

  if grep -q " $HASH$" "$SEEN" 2>/dev/null; then
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  # Append entry.
  {
    printf '\n## [CAND-%d] %s — %s\n' "$NEXT_ID" "$DATE" "$TITLE"
    printf -- '- suggested-path: `%s`\n' "$PATH_S"
    printf -- '- proposed-id: TM-?? (assign at PR time)\n'
    printf -- '- source-session: `%s` (trigger=%s)\n' "$SID" "$TRG"
    printf -- '- distilled-at: %s\n' "$TS_LOG"
    printf -- '- status: pending\n'
    printf -- '- summary: %s\n' "$SUMMARY"
    if [ -n "$EVIDENCE" ] && [ "$EVIDENCE" != "null" ]; then
      printf -- '- evidence-excerpt: |\n'
      printf '%s\n' "$EVIDENCE" | sed 's/^/    /'
    fi
  } >> "$QUEUE"

  echo "$NOW_EPOCH $HASH" >> "$SEEN"
  NEXT_ID=$((NEXT_ID + 1))
  ADDED=$((ADDED + 1))
done

echo "wiki-queue session=$SID added=$ADDED skipped(dup)=$SKIPPED total_in=$N"
