#!/usr/bin/env bash
# installer-gen-stamp.sh — generation stamps for installer-managed cron
# entries (#1081).
#
# An installer-managed cron entry is rendered once and then frozen: nothing
# re-runs the installer when the repo moves, so a fix that changes the
# rendered line never reaches the node (#996 sat 4 days, #1067 needed a manual
# 10-node rollout). The stamp makes that drift visible: each managed marker
# carries `gen=h_<sha256:12>` computed from the CONTENT of the files that
# render the entry (the installer script itself, plus any shared lib passed as
# an extra input), and ccc-doctor compares it against the stamp recomputed
# from the current checkout. Mismatch ⇒ the installed entry was generated by
# older code.
#
# Design rules:
#   - Content-only digest. No file paths and no git metadata go in, so the
#     stamp is identical across checkout locations and works from tarball
#     installs or single-file copies with identical content.
#   - The stamp token is appended AFTER the marker token, so every existing
#     substring-based removal (`grep -vF "$MARKER"`, awk `index($0, marker)`)
#     keeps working on stamped lines, and stamped installers keep removing
#     unstamped legacy lines.
#   - sha256sum and the python3 fallback MUST agree: apply-time stamping and
#     doctor-time comparison may run in different environments. Both use
#     hash-of-hashes (per-file sha256 hexdigests, one per line, hashed again),
#     which also avoids concatenation boundary ambiguity.

# ccc_installer_gen_inputs <installer-abspath>
#   Prints the canonical stamp content inputs, one per line, in a stable
#   order: the installer itself, then the shared rendering libs it depends on.
#   The list is owned HERE, once — installers stamp with it, and ccc-doctor /
#   ccc-self-update recompute with it, so the three never disagree about what
#   a stamp describes. (A disagreement would surface as permanent false drift
#   and a re-apply every self-update tick.)
#
#   installer-gen-stamp.sh itself is deliberately NOT an input: it is the
#   measuring instrument, not a rendering input. If the stamp algorithm ever
#   changes, pre-change stamps legitimately fail comparison and the fleet
#   re-stamps through self-update re-apply — that is the designed failure
#   mode, not a bug.
ccc_installer_gen_inputs() {
  [ -n "${1:-}" ] || { echo "installer-gen-stamp: gen inputs need an installer path" >&2; return 2; }
  local self="$1" dir extras lib
  dir="$(cd "$(dirname "$self")" && pwd)" || return 1
  # Extra rendering inputs per installer (basename → space-separated lib
  # basenames under scripts/lib). Adding a shared-lib dependency to an
  # installer means adding it here too, or a lib-only change renders new
  # entries while the stamp stays put — the exact blind spot #1081 closed.
  extras=""
  case "$(basename "$self")" in
    # The three crontab installers render through the shared cron lib (#1077).
    # (install-cost-ledger-cron.sh also sources the lib but is deliberately NOT
    # listed: adding it would re-stamp 12 already-correct fleet entries.)
    install-memory-refresh-cron.sh|install-pr-status-poll-cron.sh|install-skill-autosave-cron.sh|install-fleet-skills-sync-cron.sh)
      extras="installer-cron-common.sh" ;;
  esac
  printf '%s\n' "$self"
  for lib in $extras; do
    printf '%s\n' "$dir/lib/$lib"
  done
}

# ccc_installer_gen_stamp_auto <installer-abspath>
#   Stamp over the canonical inputs of ccc_installer_gen_inputs. This is the
#   call every stamper and every recomputer should make.
ccc_installer_gen_stamp_auto() {
  local inputs=()
  mapfile -t inputs < <(ccc_installer_gen_inputs "$1") || return 2
  ccc_installer_gen_stamp "${inputs[@]}"
}

# ccc_installer_gen_stamp <content-input> [extra-content-input ...]
#   Prints h_<12 lowercase hex>. Every input must be a readable regular file
#   (no symlinks — the stamp must describe the bytes the installer actually
#   read). The first input is conventionally the installer script itself;
#   shared rendering libs (see ccc_installer_gen_inputs) are passed as extra
#   inputs so a lib change re-stamps the entries rendered through it.
ccc_installer_gen_stamp() {
  [ "$#" -ge 1 ] || { echo "installer-gen-stamp: no content input given" >&2; return 2; }
  local f
  for f in "$@"; do
    if [ -L "$f" ] || [ ! -f "$f" ] || [ ! -r "$f" ]; then
      echo "installer-gen-stamp: content input missing or unsafe: $f" >&2
      return 1
    fi
  done
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$@" | cut -d' ' -f1 | sha256sum | cut -c1-12 | sed 's/^/h_/'
  elif command -v python3 >/dev/null 2>&1; then
    python3 - "$@" <<'PY'
import hashlib
import sys

outer = hashlib.sha256()
for path in sys.argv[1:]:
    inner = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            inner.update(chunk)
    outer.update(inner.hexdigest().encode("ascii"))
    outer.update(b"\n")
print("h_" + outer.hexdigest()[:12])
PY
  else
    echo "installer-gen-stamp: need sha256sum or python3" >&2
    return 3
  fi
}

# --- install records (#1081 phase 2) -----------------------------------------
# A successful `--apply` leaves an install record in the node's state dir so
# ccc-self-update can replay the EXACT resolved invocation when the stamp
# drifts. Records are bookkeeping, never secrets: installer relpath, marker,
# replay argv (resolved values — e.g. the effective --schedule, not the
# operator's env), the gen stamped at apply time, and a timestamp.
#
# Record writes are best-effort: a failed write must not fail an --apply that
# already changed the crontab, so helpers return non-zero and callers only
# warn. File perms are 0600 under the (already owner-only) state dir.

# ccc_installer_record_path <state-dir> <installer-abspath>
ccc_installer_record_path() {
  local base
  base="$(basename "$2")"
  base="${base%.sh}"
  printf '%s/%s.json' "$1" "$base"
}

# ccc_installer_record_write <state-dir> <installer-abspath> <marker> <gen> -- [argv...]
ccc_installer_record_write() {
  local state_dir="$1" self="$2" marker="$3" gen="$4"
  shift 4
  [ "${1:-}" = "--" ] && shift
  [ -d "$state_dir" ] || mkdir -p "$state_dir" 2>/dev/null || return 1
  python3 - "$state_dir" "$self" "$marker" "$gen" "$@" <<'PY'
import json
import os
import sys
import tempfile
import time

state_dir, self_path, marker, gen, argv = (
    sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5:],
)
base = os.path.basename(self_path)
if base.endswith(".sh"):
    base = base[:-3]
record = {
    "schema": "ccc.install-record.v1",
    "installer": "scripts/" + os.path.basename(self_path),
    "marker": marker,
    "gen": gen,
    "argv": argv,
    "applied_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
}
fd, tmp = tempfile.mkstemp(prefix="." + base + ".", dir=state_dir)
try:
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        json.dump(record, fh, ensure_ascii=False, separators=(",", ":"))
        fh.write("\n")
    os.chmod(tmp, 0o600)
    os.replace(tmp, os.path.join(state_dir, base + ".json"))
finally:
    try:
        os.unlink(tmp)
    except OSError:
        pass
PY
}

# ccc_installer_record_remove <state-dir> <installer-abspath>
# A deliberate --remove must also drop the record, or the next self-update
# re-apply would resurrect an entry the operator just removed.
ccc_installer_record_remove() {
  local path
  path="$(ccc_installer_record_path "$1" "$2")" || return 1
  rm -f -- "$path"
}
