#!/usr/bin/env bash
# installer-gen-stamp.sh — generation stamps for installer-managed cron
# entries (#1081).
#
# An installer-managed cron entry is rendered once and then frozen: nothing
# re-runs the installer when the repo moves, so a fix that changes the
# rendered line never reaches the node (#996 sat 4 days, #1067 needed a manual
# 10-node rollout). The stamp makes that drift visible: each managed marker
# carries `gen=h_<sha256:12>` computed from the CONTENT of the files that
# render the entry (the installer script itself, plus any shared lib passed as
# an extra input), and ccc-doctor compares it against the stamp recomputed
# from the current checkout. Mismatch ⇒ the installed entry was generated by
# older code.
#
# Design rules:
#   - Content-only digest. No file paths and no git metadata go in, so the
#     stamp is identical across checkout locations and works from tarball
#     installs or single-file copies with identical content.
#   - The stamp token is appended AFTER the marker token, so every existing
#     substring-based removal (`grep -vF "$MARKER"`, awk `index($0, marker)`)
#     keeps working on stamped lines, and stamped installers keep removing
#     unstamped legacy lines.
#   - sha256sum and the python3 fallback MUST agree: apply-time stamping and
#     doctor-time comparison may run in different environments. Both use
#     hash-of-hashes (per-file sha256 hexdigests, one per line, hashed again),
#     which also avoids concatenation boundary ambiguity.

# ccc_installer_gen_stamp <content-input> [extra-content-input ...]
#   Prints h_<12 lowercase hex>. Every input must be a readable regular file
#   (no symlinks — the stamp must describe the bytes the installer actually
#   read). The first input is conventionally the installer script itself;
#   when the cron-installer shared lib (#1077) lands, installers that source
#   it pass it as an extra input so a lib change re-stamps their entries.
ccc_installer_gen_stamp() {
  [ "$#" -ge 1 ] || { echo "installer-gen-stamp: no content input given" >&2; return 2; }
  local f
  for f in "$@"; do
    if [ -L "$f" ] || [ ! -f "$f" ] || [ ! -r "$f" ]; then
      echo "installer-gen-stamp: content input missing or unsafe: $f" >&2
      return 1
    fi
  done
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$@" | cut -d' ' -f1 | sha256sum | cut -c1-12 | sed 's/^/h_/'
  elif command -v python3 >/dev/null 2>&1; then
    python3 - "$@" <<'PY'
import hashlib
import sys

outer = hashlib.sha256()
for path in sys.argv[1:]:
    inner = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            inner.update(chunk)
    outer.update(inner.hexdigest().encode("ascii"))
    outer.update(b"\n")
print("h_" + outer.hexdigest()[:12])
PY
  else
    echo "installer-gen-stamp: need sha256sum or python3" >&2
    return 3
  fi
}
