#!/usr/bin/env bash
# skill-suggest scanner — deterministic, human-in-the-loop.
# Scans Claude Code transcripts for frequently-repeated command "shapes" and writes a
# ranked candidate report. It NEVER authors skills itself — it only proposes; a human
# (via the `/skill-suggest` skill) decides what becomes a SKILL.md.
#
# Output: /root/.claude/state/skill-candidates.md
# Tune:   SKILL_SUGGEST_MIN (min frequency to surface, default 4)
set -uo pipefail

PROJ="${CLAUDE_PROJECTS_DIR:-/root/.claude/projects}"
OUT="${SKILL_SUGGEST_OUT:-/root/.claude/state/skill-candidates.md}"
MIN="${SKILL_SUGGEST_MIN:-4}"
SKILLS_DIR="${CLAUDE_SKILLS_DIR:-/root/.claude/skills}"
mkdir -p "$(dirname "$OUT")"

# Existing skills (so we can flag candidates already covered).
existing="$(ls -1 "$SKILLS_DIR" 2>/dev/null | tr '\n' ' ')"

# 1) Extract every Bash command from every transcript (robust against malformed lines),
# 2) normalize each to a coarse "shape" (program [+ subcommand]) — args/paths/urls stripped.
# Only these programs count as "procedure" signal (allowlist) — everything else
# (echo/grep/ls/cat/sed/heredoc bodies/cd targets...) is narration noise and is dropped.
# Multi-line commands are collapsed to one line in jq so heredoc bodies aren't counted.
shapes="$(
  find "$PROJ" -name '*.jsonl' 2>/dev/null -print0 \
    | xargs -0 -r cat 2>/dev/null \
    | jq -Rrc 'fromjson? | (.message.content[]? // empty)
               | select(.type=="tool_use" and .name=="Bash")
               | (.input.command | gsub("[\n\t]+";" "))' 2>/dev/null \
    | awk '
      BEGIN{
        allow=" git gh npm npx claude docker kubectl systemctl pip wiki-agent openclaw cargo go make python python3 node "
        multi=" git gh npm npx claude docker kubectl systemctl pip wiki-agent openclaw cargo go make "
      }
      {
        n=split($0,a,/[ \t]+/); prog=""; subc=""
        for(i=1;i<=n;i++){
          t=a[i]
          if(t=="") continue
          if(t ~ /^[A-Za-z_][A-Za-z0-9_]*=/) continue          # env assignment
          if(t=="cd"){ i++; continue }                         # skip cd AND its target
          if(t=="sudo"||t=="time"||t=="command"||t=="env"||t=="nohup"||t=="setsid"||t=="exec"){ continue }
          if(t=="timeout"){ i++; continue }                    # skip its duration arg
          if(t=="&&"||t=="||"||t==";"||t=="|"||t=="!"||t=="{"||t=="("||t=="}"||t==")") continue
          if(prog==""){ prog=t; continue }
          if(t ~ /^-/) continue                                # flag
          subc=t; break
        }
        if(prog=="") next
        base=prog; gsub(/.*\//,"",base)                        # strip path
        keep=0
        if(index(allow," " base " ")>0) keep=1                 # allowlisted tool
        else if(prog ~ /\.sh($|\?)/ || base ~ /\.sh$/) { keep=1; base=base" (script)" }  # project scripts
        if(!keep) next
        shape=base
        if(index(multi," " base " ")>0 && subc!="" && subc !~ /^-/){
          gsub(/.*\//,"",subc); shape=base" "subc
        }
        print shape
      }' \
    | sort | uniq -c | sort -rn
)"

total_cmds="$(printf '%s\n' "$shapes" | awk '{s+=$1} END{print s+0}')"
sessions="$(find "$PROJ" -name '*.jsonl' 2>/dev/null | wc -l | tr -d ' ')"

{
  echo "# skill-suggest candidates"
  echo
  echo "> Auto-generated by skill-suggest/scan.sh. Heuristic only — repeated command **shapes**,"
  echo "> not verified procedures. Review with the \`/skill-suggest\` skill; author skills only on approval."
  echo
  echo "- transcripts scanned: ${sessions}"
  echo "- total Bash commands: ${total_cmds}"
  echo "- min frequency surfaced: ${MIN}"
  echo "- existing skills (already covered): ${existing:-none}"
  echo
  echo "## Repeated command shapes (count >= ${MIN})"
  echo
  printf '%s\n' "$shapes" | awk -v min="$MIN" '
    $1>=min { printf("- `%s` x%d\n", substr($0, index($0,$2)), $1) }'
  echo
  echo "## Reading"
  echo "- A cluster of related high-count shapes (same tool/program) often = a recurring procedure worth a skill."
  echo "- Ignore shapes already covered by an existing skill above."
  echo "- The \`/skill-suggest\` skill turns an approved cluster into a SKILL.md."
} > "$OUT"

echo "[skill-suggest] wrote $OUT (sessions=$sessions, cmds=$total_cmds)"
